Урок_0
vladkorolkov/dotnetlearn pull request #1
Opened 2022-01-25 12:27 UTC by vladkorolkov

Долго ковырялся, но вроде получилось. 
Помимо перечисленных в задании методов реализовал поиск по введенному названию.

2022-01-25 20:03 UTC, navferty requested changes

2022-01-25 20:03 UTC, navferty commented on dotnetlearn/lesson_0/Program.cs
> +            var result = q.FirstOrDefault();
Тут применяются подряд два варианта синтаксиса LINQ: query-синтаксис (`from ... in ... where ...`) и method chain (`FirstOrDefault`)
Предлагаю придерживаться одного варианта, например method chain.

Также `FirstOrDefault` может сам принимать предикат с условием поиска, тогда `Where` будет лишним
https://docs.microsoft.com/dotnet/api/system.linq.enumerable.firstordefault

2022-01-25 20:03 UTC, navferty commented on dotnetlearn/lesson_0/Program.cs
> +        public static Factory[] GetAllFactories(List<Factory> factories)
Также непонятен логический смысл этого метода. Переупаковать из List в массив: зачем?

2022-01-25 20:03 UTC, navferty commented on dotnetlearn/lesson_0/Program.cs
> +        public static int GetTotalVolume(List<Tank> tanks)
Предполагается не посчитать количество, а найти **суммарный объем** резервуаров

2022-01-25 20:03 UTC, navferty commented on dotnetlearn/lesson_0/Program.cs
> +                        Console.WriteLine("Общий объем резервуаров: " + totaVolume + "\nДля нового поиска нажмите любоую клавишу");
Выше используется [интерполяция строк](https://docs.microsoft.com/dotnet/csharp/language-reference/tokens/interpolated) (с помощью символа `$`). В остальных местах вместо конкатенации можно придерживаться этого же способа, он представляется более удобным

2022-01-26 08:20 UTC, vladkorolkov commented on dotnetlearn/lesson_0/Program.cs
> +        public static Tank[] GetTank(List<Tank> Tanks)
В задании просили вернуть именно массив. Но я изначально все объекты сделал в коллекции и сомневался тоже нужны ли эти методы)

2022-01-26 09:24 UTC, vladkorolkov commented on dotnetlearn/lesson_0/Models/Factory.cs
> +        public int id { get; set; }
Спасибо!

2022-01-26 09:26 UTC, vladkorolkov commented on dotnetlearn/lesson_0/Program.cs
> +                        Console.WriteLine("Общий объем резервуаров: " + totaVolume + "\nДля нового поиска нажмите любоую клавишу");
Ага, спасибо, невнимательность)

2022-01-26 15:20 UTC, merged